/*************************************************************************//**
 *****************************************************************************
 * @file   clock.c
 * @brief  
 * @author Forrest Y. Yu
 * @date   2005
 *****************************************************************************
 *****************************************************************************/

#include "type.h"
#include "stdio.h"
#include "const.h"
#include "protect.h"
#include "string.h"
#include "fs.h"
#include "proc.h"
#include "tty.h"
#include "console.h"
#include "global.h"
#include "proto.h"


/*****************************************************************************
 *                                clock_handler
 *****************************************************************************/
/**
 * <Ring 0> This routine handles the clock interrupt generated by 8253/8254
 *          programmable interval timer.
 * 
 * @param irq The IRQ nr, unused here.
 *****************************************************************************/
PUBLIC void clock_handler(int irq)
{
	if (++ticks >= MAX_TICKS)
		ticks = 0;

	/*-------------------------------------------------------------------*
	 * B 级新增:调度统计                                                *
	 *   - 正在运行的进程累计其占用 CPU 的 tick 数;                     *
	 *   - 其余处于就绪态却没拿到 CPU 的进程累计等待 tick 数。           *
	 *   (用于 ps 命令展示 CPU 占用与公平性)                           *
	 *-------------------------------------------------------------------*/
	if (p_proc_ready->p_flags == 0)
		p_proc_ready->cpu_ticks++;
	{
		struct proc* q;
		for (q = &FIRST_PROC; q <= &LAST_PROC; q++)
			if (q->p_flags == 0 && q != p_proc_ready)
				q->wait_ticks++;
	}

	if (p_proc_ready->ticks)
		p_proc_ready->ticks--;

	if (key_pressed)
		inform_int(TASK_TTY);

	if (k_reenter != 0) {
		return;
	}

	/*-------------------------------------------------------------------*
	 * B 级新增:优先级老化 —— 每隔 SCHED_BOOST_TICKS 个 tick 把所有     *
	 * 进程提回第 0 层,防止低优先级进程饿死(MLFQ 规则 5)。           *
	 *-------------------------------------------------------------------*/
	if (ticks % SCHED_BOOST_TICKS == 0)
		sched_boost();

	if (p_proc_ready->ticks > 0) {
		return;
	}

	/*-------------------------------------------------------------------*
	 * B 级新增:时间片用尽 -> 降级。                                    *
	 * 用完整个时间片说明该进程是 CPU 密集型,把它降到下一层(优先级    *
	 * 更低、但下次时间片更长)。系统任务(is_user==0)不参与降级,      *
	 * 始终保持在最高优先级,以保证 IPC 与驱动的实时性。然后重新发放    *
	 * 一个(新层级的)时间片并触发重新调度。                          *
	 *-------------------------------------------------------------------*/
	if (p_proc_ready->is_user &&
	    p_proc_ready->sched_level < NR_SCHED_LEVELS - 1)
		p_proc_ready->sched_level++;
	p_proc_ready->ticks = SCHED_QUANTUM(p_proc_ready->sched_level);

	schedule();

}

/*****************************************************************************
 *                                milli_delay
 *****************************************************************************/
/**
 * <Ring 1~3> Delay for a specified amount of time.
 * 
 * @param milli_sec How many milliseconds to delay.
 *****************************************************************************/
PUBLIC void milli_delay(int milli_sec)
{
        int t = get_ticks();

        while(((get_ticks() - t) * 1000 / HZ) < milli_sec) {}
}

/*****************************************************************************
 *                                init_clock
 *****************************************************************************/
/**
 * <Ring 0> Initialize 8253/8254 PIT (Programmable Interval Timer).
 * 
 *****************************************************************************/
PUBLIC void init_clock()
{
        /* 初始化 8253 PIT */
        out_byte(TIMER_MODE, RATE_GENERATOR);
        out_byte(TIMER0, (u8) (TIMER_FREQ/HZ) );
        out_byte(TIMER0, (u8) ((TIMER_FREQ/HZ) >> 8));

        put_irq_handler(CLOCK_IRQ, clock_handler);    /* 设定时钟中断处理程序 */
        enable_irq(CLOCK_IRQ);                        /* 让8259A可以接收时钟中断 */
}


